<a href="https://colab.research.google.com/github/Gustav1814/A.I-and-ML-Learning/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors

Tensors are fundamental multi-dimensional arrays used in machine learning to represent data and perform mathematical operations, acting as a generalization of scalars, vectors, and matrices.

Data Type = FLoat32.

Suitable for deep learning than a numpy array

In [4]:
import torch
import numpy as np

**LISTS**

In [6]:
list = [[1,2,3,4,5], [6,7,8,9,10]]
list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY ARRAY**

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.3664977 , 0.90931031, 0.68675253, 0.04140125],
       [0.95644407, 0.82446832, 0.75472751, 0.67439799],
       [0.49019971, 0.82186492, 0.37541928, 0.52060208]])

In [8]:
np1.dtype

dtype('float64')

**TENSORS**

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0348,  0.6843, -0.5073, -0.0090],
        [-0.4517, -0.3595, -0.6790, -2.3218],
        [ 1.2248,  0.8870,  0.2974, -0.2829]])

In [12]:
tensor_3d = torch.zeros (2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])



> Create Tensor out of Numpy Arrays






In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3665, 0.9093, 0.6868, 0.0414],
        [0.9564, 0.8245, 0.7547, 0.6744],
        [0.4902, 0.8219, 0.3754, 0.5206]], dtype=torch.float64)