<a href="https://colab.research.google.com/github/Gustav1814/A.I-and-ML-Learning/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **TENSOR MATH OPERATIONS**


*   ADD, SUBTRACT, MULTIPLY, DIVIDE, REMIANDER, EXPONENTS
*   SHORTHAND AND LONGHAND

*   REASSINGMENT





In [2]:
import torch
import numpy as np

In [3]:
tensor_A = torch.tensor([1,2,3,4])
tensor_B = torch.tensor([5,6,7,8])

**Addition**

In [4]:
tensor_A + tensor_B

tensor([ 6,  8, 10, 12])



> Add longhand



In [5]:
torch.add(tensor_A, tensor_B)


tensor([ 6,  8, 10, 12])

**Subtraction**

In [6]:
tensor_B - tensor_A

tensor([4, 4, 4, 4])

In [7]:
torch.subtract(tensor_B, tensor_A)

tensor([4, 4, 4, 4])

**Multiplication**

In [8]:
tensor_A * tensor_B

tensor([ 5, 12, 21, 32])

In [9]:
torch.mul(tensor_A, tensor_B)

tensor([ 5, 12, 21, 32])

**Division**

In [10]:
tensor_B / tensor_A

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensor_B, tensor_A)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

**Remainder Modulus**

In [12]:
tensor_B % tensor_A

tensor([0, 0, 1, 0])

In [14]:
torch.remainder(tensor_B, tensor_A)

tensor([0, 0, 1, 0])

**Exponents**

In [15]:
torch.pow(tensor_A, tensor_B)

tensor([    1,    64,  2187, 65536])

**Reassignment**

In [16]:
tensor_A

tensor([1, 2, 3, 4])

In [18]:
tensor_A - tensor_A + tensor_B

tensor([5, 6, 7, 8])

In [20]:
tensor_A.add_(tensor_B)

tensor([ 6,  8, 10, 12])

In [21]:
tensor_A

tensor([ 6,  8, 10, 12])