<a href="https://colab.research.google.com/github/Gustav1814/A.I-and-ML-Learning/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
mytorch = torch.arange(20)
mytorch


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

**RESHAPE AND VIEW**

In [ ]:
mytorch = mytorch.reshape(4,5)
mytorch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

**Reshape when we Dont know the number of items using -1**

In [ ]:
mytorch2 = torch.arange(10)
mytorch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mytorch2 = mytorch2.reshape (2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
mytorch2 = mytorch2.reshape (-1,5)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
mytorch3 = torch.arange(15)
mytorch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])



> using View



In [ ]:
mytoorch4 = mytorch3.view(3,5)
mytoorch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

**With Reshape and view, They will Update**

In [ ]:
mytorch5 = torch.arange(10)
mytorch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mytorch6 = mytorch5.reshape(2,-1)
mytorch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
mytorch5[1] = 4141
mytorch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
mytorch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

**Slices**



In [ ]:
mytorch7 = torch.arange(10)
mytorch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Grab a specific item**

In [ ]:
mytorch7[7]

tensor(7)

**Grab Slices**

In [ ]:
mytorch8 = mytorch7.reshape(5,2)
mytorch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
mytorch8[:,1]

tensor([1, 3, 5, 7, 9])

**RETURN COLUMN**

In [27]:
mytorch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])