# Feature Scaling 

- **Definition:** Adjusting numeric features so they share a common scale.
- **Purpose:** Prevents features with larger ranges from dominating model training.
- **When to use:** For models that rely on distance or gradient-based optimization (e.g., k-NN, SVM, logistic regression, neural networks).
- **Common methods:** Standardization (z-score), Min–Max normalization.
- **Tip:** Fit the scaler on the training set and apply it to validation/test sets to avoid data leakage.


In [ ]:
import pandas as pd

In [27]:
df = pd.read_csv('datasets/placement_data.csv')
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0


In [28]:
df = df[['salary', 'mba_p', 'etest_p']]
df

,salary,mba_p,etest_p
0,270000.0,58.80,55.0
1,200000.0,66.28,86.5
2,250000.0,57.80,75.0
3,NaN,59.43,66.0
4,425000.0,55.50,96.8
...,...,...,...
210,400000.0,74.49,91.0
211,275000.0,53.62,74.0
212,295000.0,69.72,59.0
213,204000.0,60.23,70.0


# Why Feature Scaling Matters

**Problem:** The `salary` column has values much larger than `mba_p` and `etest_p`. When features have different scales, many models (especially distance-based or gradient-based algorithms) treat larger-valued features as more important.

- **Effect:** Models can become dominated by `salary`, producing biased weights and poor generalization.
- **Goal:** Give each feature equal importance by putting them on a comparable scale.

**Common Solutions:**
- **Standardization** — subtract mean and divide by standard deviation (`StandardScaler`).
- **Min–Max Scaling** — rescale to a specific range, usually [0, 1] (`MinMaxScaler`).

**Best Practice:** Fit the scaler on the training set and apply it to the test set to avoid data leakage.



----------
# **Normalization, MIN MAX Scaling**

- Normalization is a scalin technique in which values are shifted and rescaled.
- so that they end up rangin between 0 and 1. It is also known as Min Max Scalingg

**Formula (rescale to [0, 1]):**

$$
x' = \frac{x - x_{\min}}{x_{\max} - x_{\min}}
$$

**General form (range [a, b]):**

$$
x' = a + \frac{(x - x_{\min})(b - a)}{x_{\max} - x_{\min}}
$$

*If $x_{\max} = x_{\min}$ (constant feature), set $x' = a$ (or $0$ for $[0,1]$) to avoid division by zero.*

-------------
# **Applyin Normalization Min-Max Scaling**

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scalar = MinMaxScaler()
df_scaled = scalar.fit_transform(df)

In [31]:
df_scaled

array([[0.09459459, 0.28448276, 0.10416667],
       [0.        , 0.56484258, 0.76041667],
       [0.06756757, 0.2470015 , 0.52083333],
       [       nan, 0.30809595, 0.33333333],
       [0.30405405, 0.1607946 , 0.975     ],
       [       nan, 0.01386807, 0.10416667],
       [       nan, 0.07796102, 0.50583333],
       [0.07027027, 0.40967016, 0.35416667],
       [0.04189189, 0.37781109, 0.86125   ],
       [       nan, 0.03748126, 0.08333333],
       [0.08108108, 0.36131934, 0.25      ],
       [0.06756757, 0.46814093, 0.20833333],
       [       nan, 0.51836582, 0.25      ],
       [0.02432432, 0.65292354, 0.375     ],
       [       nan, 0.14055472, 0.54166667],
       [0.        , 0.50412294, 0.45833333],
       [0.13513514, 0.42466267, 0.20833333],
       [       nan, 0.60232384, 0.20833333],
       [       nan, 0.48238381, 0.375     ],
       [0.04864865, 1.        , 0.01      ],
       [0.08783784, 0.20577211, 0.        ],
       [0.26081081, 0.66904048, 0.9375    ],
       [0.

In [32]:
df_scaled = pd.DataFrame(data = df_scaled, columns = df.columns)
df_scaled

,salary,mba_p,etest_p
0,0.094595,0.284483,0.104167
1,0.000000,0.564843,0.760417
2,0.067568,0.247001,0.520833
3,NaN,0.308096,0.333333
4,0.304054,0.160795,0.975000
...,...,...,...
210,0.270270,0.872564,0.854167
211,0.101351,0.090330,0.500000
212,0.128378,0.693778,0.187500
213,0.005405,0.338081,0.416667


# **Train Test Split**

In [33]:
df

,salary,mba_p,etest_p
0,270000.0,58.80,55.0
1,200000.0,66.28,86.5
2,250000.0,57.80,75.0
3,NaN,59.43,66.0
4,425000.0,55.50,96.8
...,...,...,...
210,400000.0,74.49,91.0
211,275000.0,53.62,74.0
212,295000.0,69.72,59.0
213,204000.0,60.23,70.0


In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X = df.drop('salary', axis=1)
y = df['salary']

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

--------------------------------------------------------------------
# **Feature Scalling: Normalization Min MAx Scalar**

In [37]:
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [38]:
X_train_scaled

array([[0.15742129, 0.45833333],
       [0.40442279, 0.10416667],
       [0.41041979, 0.94708333],
       [0.34482759, 0.125     ],
       [0.87256372, 0.85416667],
       [0.21814093, 0.35416667],
       [0.5565967 , 0.525     ],
       [0.52623688, 1.        ],
       [0.21176912, 0.07708333],
       [0.85457271, 0.9875    ],
       [0.87518741, 0.625     ],
       [0.28485757, 0.47916667],
       [0.0029985 , 0.5625    ],
       [1.        , 0.01      ],
       [0.63193403, 0.41666667],
       [0.66791604, 0.91479167],
       [0.22601199, 0.20833333],
       [0.30097451, 0.60416667],
       [0.01386807, 0.10416667],
       [0.38868066, 0.58333333],
       [0.58733133, 0.375     ],
       [0.5149925 , 0.133125  ],
       [0.77773613, 0.79166667],
       [0.34595202, 0.66666667],
       [0.22076462, 0.826875  ],
       [0.18290855, 0.75      ],
       [0.32233883, 0.52083333],
       [0.26649175, 0.29166667],
       [0.51836582, 0.25      ],
       [0.43215892, 0.4375    ],
       [0.

In [39]:
X_test_scaled

array([[0.05997001, 0.78229167],
       [0.69377811, 0.1875    ],
       [0.77061469, 0.95833333],
       [0.25074963, 0.10416667],
       [0.50412294, 0.45833333],
       [0.35344828, 0.20833333],
       [0.28410795, 0.20833333],
       [0.32008996, 0.75      ],
       [0.61769115, 0.625     ],
       [0.12068966, 0.16666667],
       [0.39955022, 0.20833333],
       [0.20577211, 0.04166667],
       [0.43928036, 0.10416667],
       [0.03748126, 0.08333333],
       [0.36656672, 0.38979167],
       [0.35532234, 0.78125   ],
       [0.55584708, 0.28729167],
       [0.48238381, 0.375     ],
       [0.42241379, 0.75      ],
       [0.27173913, 0.39416667],
       [0.75787106, 0.66666667],
       [0.37781109, 0.20833333],
       [0.62893553, 0.52083333],
       [0.52923538, 0.54166667],
       [0.26311844, 0.10416667],
       [0.45052474, 0.45833333],
       [0.58958021, 0.95104167],
       [0.42466267, 0.20833333],
       [0.57421289, 0.16666667],
       [0.37818591, 0.125     ],
       [0.

--------------
# When to apply feature scaling

- **K-Nearest Neighbors (KNN):** KNN relies on distance metrics; scaling significantly affects performance.
- **Support Vector Machines (SVM):** SVM uses distances between points; feature scaling is essential for correct margins.
- **K-Means Clustering:** Clustering depends on distances; unscaled features bias cluster assignments.
- **Principal Component Analysis (PCA):** PCA is sensitive to feature variances; scale features before computing components.
- **Gradient Descent–based algorithms:** Models like Linear/Logistic Regression and Neural Networks converge faster and more reliably with scaled inputs.
- **Gaussian Mixture Models (GMM):** Like K-Means, GMMs use distance metrics; scaling helps model the underlying distribution correctly.

**Quick rule of thumb:** If the algorithm uses distances or gradient-based optimization, apply feature scaling.

-----------------------------------------------------------------------------------------------------------------------------------------------

-----

# Feature Scaling — Standardization (Z-score)

**What it is:**
- Standardization rescales features so they have mean 0 and standard deviation 1.
- Also called *z-score normalization*.

**Formula (per feature):**

$$
z = \frac{x - \mu}{\sigma}
$$

where:
- $x$ is the original feature value,
- $\mu$ is the mean of the feature (usually computed on the training set),
- $\sigma$ is the standard deviation of the feature (usually computed on the training set).

To invert the transform (recover original values):

$$
x = z\sigma + \mu
$$

**Why use standardization:**
- Centers features around zero and gives them unit variance, which helps many algorithms behave better.
- Improves convergence speed for gradient-based optimizers (e.g., neural networks, logistic regression).
- Makes regularization penalties (L1, L2) act consistently across features.
- Necessary for algorithms that assume standardized input (e.g., PCA, some implementations of SVM).

**When to prefer standardization vs Min–Max:**
- Use **standardization** when your data is Gaussian-like or your model assumes zero-centered inputs (linear models, logistic regression, neural networks, PCA, SVM).
- Use **Min–Max scaling** when you need a bounded range (e.g., [0,1]) or when features are already roughly uniformly distributed.
- If your data contains many outliers, consider **RobustScaler** (uses median and IQR) instead of StandardScaler.

**Best practices:**
- Always *fit* the scaler on the training set only, then *transform* the validation/test sets to avoid data leakage:

- After standardization, inspect means and variances to confirm transformation (training mean ≈ 0, training std ≈ 1).

**Summary:**
- Standardization (z-score) centers features and sets unit variance. Use it for models sensitive to feature centering/scaling and for better optimizer behavior; prefer robust methods if outliers dominate.

-----------------------------

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('datasets/social_network_ads.csv')
df

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [8]:
df.drop(['User ID'], axis=1, inplace=True) # To drop the column 'User ID' from the dataset as it is not useful for our analysis
df

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0
...,...,...,...,...
395,Female,46,41000,1
396,Male,51,23000,1
397,Female,50,20000,1
398,Male,36,33000,0


In [9]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0}) # To convert the categorical variable 'Gender' into numerical values for analysis
df

,Gender,Age,EstimatedSalary,Purchased
0,1,19,19000,0
1,1,35,20000,0
2,0,26,43000,0
3,0,27,57000,0
4,1,19,76000,0
...,...,...,...,...
395,0,46,41000,1
396,1,51,23000,1
397,0,50,20000,1
398,1,36,33000,0


# **Train Test Split**

In [12]:
from sklearn.model_selection import train_test_split

X = df.drop('Purchased', axis=1)
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train

,Gender,Age,EstimatedSalary
3,0,27,57000
18,1,46,28000
202,0,39,134000
250,0,44,39000
274,0,57,26000
...,...,...,...
71,0,24,27000
106,0,26,35000
270,0,43,133000
348,1,39,77000


*As You can see model will dominate to ***salary*** column because of higher value so we need feature scaling*

In [14]:
y_train

3      0
18     1
202    1
250    0
274    1
      ..
71     0
106    0
270    0
348    0
102    0
Name: Purchased, Length: 320, dtype: int64

# **Applying Standar Scalar**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

NameError: name 'scaler' is not defined